#!/usr/bin/env bash

if brew cask info "atom" | grep "Not installed" > /dev/null; then
  echo ""
  echo "Installing Atom: The hackable text editor for the 21st Century."
  brew cask install atom
fi

sleep 1

echo ""
open -a /Applications/Atom.app
sleep 1
killall Atom

echo "Installing Atom Packages:"
echo ""
apm angularjs
apm angularjs-styleguide-snippets
apm language-nginx
apm language-puppet

ATOMCONF="$HOME/.atom/config.cson"
ATOMCSS="$HOME/.atom/styles.less"

cat <<EOM >$ATOMCONF
'editor':
'atom-text-editor':
  'fontFamily': 'Menlo'
  'fontSize': 13
  'scrollPastEnd': true
  'lineHeight': 1.5
  'invisibles': {}
  'showIndentGuide': true
  editor:
    invisibles: {}
    fontFamily: "Menlo"
    showIndentGuide: true
    useShadowDOM: false
    scrollPastEnd: true
  welcome:
    showOnStartup: true
EOM

echo ""
echo "Done! Relaunching Atom, exiting Terminal..."
open -a /Applications/Atom.app
